### PR TITLE
Made the message concise to fit into discord character limits and cha…

### PR DESCRIPTION
**Pull request by vinaykrishna64**
…nged the image

### CODE REVIEW

**Review by arzulo — APPROVED** [review]
better!

**Comment by arzulo** [comment]
Condensing error message and revising the image

**Comment by apjanke** [comment]
Hmm.

I'm not sure I'm a fan of this change. I dunno about Discord character limits - I think bot responses are exempt from them - but conciseness may not be a value here. This bot boilerplate message is aimed at junior users who need a lot of handholding, so I think a longer, more broken down in to steps message may be better. And the original text's first numbered list corresponds to the numbered callouts in the image and may help the user understand those components of it; the new text's numbered list looks like it's a sequential procedure or collection of points which does not correspond to the numbered callouts in the image.

In general I value conciseness, but IMHO a lot of the text that was removed here would actually be useful to junior users. Like that whole "The remaining lines of the error message show the 'stack' of function calls that led to the error, which can be useful for tracking down more complicated issues" sentence which was deleted; that seems like good info for someone who doesn't already knows what a stack trace is, and it tells you _why_ the first couple lines may tell you the "root cause" but the rest of the lines of the error message are still there.

I have additional issues with some of the particulars of the new text, but I don't want to be a jerk here.

There may also be a tone issue here. The new text reads:

> ### How to use the error message
>
> 1. Read the error message to understand the type of mistake. Google the message if it doesn't make sense.

That's not too far from "Look at your screen and find the red text. Read it and try to understand it. Maybe google it. Don't just paste a screenshot of it in #matlab-help-1 and say 'my code isn't work. how fix? assignment is due tomorrow at noon'." I mean it's true that "look at your error message - it's the thing in red - read it, and try to understand what it means" is often what beginner users need to do, but it's kinda condescending to phrase it that bluntly, and they may not respond well to that, either in tone, or in terms of needing to have that procedure broken down in to smaller steps.

**Comment by vinaykrishna64** [comment]
The old message was good overall but the bot doesn't print anything due to discord having a 2000 character limit.

**Pull request merged**
