### PR TITLE
Adde !askgood @user bot command to give some tips and ping a user

### PR DESCRIPTION
**Pull request by EatMyPossum**
I'd like to have the bot do the sassy task of explaining how to ask questions.  
I'm not setup to do things with js, so the code is untested. It's only 4 lines though, and most of it copied from the same file. I recon a code review should take about 5s. 
I think this message is both welcomming, short (..maybe) and usefull, but changing the message is fine with me.

### CODE REVIEW

**Comment by FannoFlow** [comment]
Should the original sender's message be deleted?

Otherwise you're going to have 2 pings, one from the bot command, and one from the bot. Seems a little unnecessary.
Also would align with the current !ask command

**Comment by EatMyPossum** [comment]
I figured yeah; I like with the ask command that you can anonymously instruct users.  Figured the double ping from one message wouldn’t be too confusing. Other options (regarding deleting and having the bot ping) all have other downsides : either no ping, not anonymous (when not delete (this would be my 2nd favorite option)) , or a ping but no mention.

The ping is mostly there to solve the people straight up ignoring the bot like they do with !ask.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by FannoFlow** [comment]
Fine by me, we can see how the double ping plays out

**Comment by EatMyPossum** [comment]
Figured a silly yet (maybe) effective 5th  option; have the bot mention the user twice, such that the two pings appear to be coming from that one message.
Might (falsely, yet effectively) solve some confusion.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by EatMyPossum** [comment]
Awesome! 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Pull request merged**
